
-- Drop tables if they exist

DROP TABLE Player_Transaction CASCADE CONSTRAINTS;

DROP TABLE Bet CASCADE CONSTRAINTS;

DROP TABLE Odds CASCADE CONSTRAINTS;

DROP TABLE MatchGame CASCADE CONSTRAINTS;

DROP TABLE Team CASCADE CONSTRAINTS;

DROP TABLE Sport CASCADE CONSTRAINTS;

DROP TABLE Admin CASCADE CONSTRAINTS;

DROP TABLE Player CASCADE CONSTRAINTS;


-- PLAYER
CREATE TABLE Player (
    player_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) UNIQUE NOT NULL,
    fname VARCHAR2(50),
    lname VARCHAR2(50),
    email VARCHAR2(100) UNIQUE NOT NULL,
    password_hash VARCHAR2(100) NOT NULL,
    balance NUMBER(10,2) DEFAULT 0,
    date_joined DATE DEFAULT SYSDATE,
    date_of_birth DATE
);


-- ADMIN
CREATE TABLE Admin (
    admin_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) UNIQUE NOT NULL,
    password_hash VARCHAR2(100) NOT NULL
);

-- SPORT
CREATE TABLE Sport (
    sport_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sport_name VARCHAR2(30) UNIQUE NOT NULL
);


-- TEAM
CREATE TABLE Team (
    team_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sport_id NUMBER,
    team_name VARCHAR2(100),
    FOREIGN KEY (sport_id) REFERENCES Sport(sport_id)
);


-- MatchGame
CREATE TABLE MatchGame (
    match_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_1 NUMBER,
    team_2 NUMBER,
    admin_id NUMBER,
    match_date DATE,
    status VARCHAR2(20) CHECK (status IN ('upcoming', 'live', 'finished')),
    final_score VARCHAR2(20),
    match_location VARCHAR2(100),
    FOREIGN KEY (team_1) REFERENCES Team(team_id),
    FOREIGN KEY (team_2) REFERENCES Team(team_id),
    FOREIGN KEY (admin_id) REFERENCES Admin(admin_id)
);


-- ODDS
CREATE TABLE Odds (
    odds_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id NUMBER,
    admin_id NUMBER,
    team_1_odds NUMBER(5,2),
    team_2_odds NUMBER(5,2),
    draw_odds NUMBER(5,2),
    odds_date DATE DEFAULT SYSDATE,
    FOREIGN KEY (match_id) REFERENCES MatchGame(match_id),
    FOREIGN KEY (admin_id) REFERENCES Admin(admin_id)
);

-- BET
CREATE TABLE Bet (
    bet_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id NUMBER,
    match_id NUMBER,
    odds_id NUMBER,
    bet_type VARCHAR2(20),
    bet_amount NUMBER(10,2),
    potential_payout NUMBER(10,2),
    bet_status VARCHAR2(20) CHECK (bet_status IN ('pending', 'won', 'lost', 'canceled')),
    time_placed TIMESTAMP DEFAULT SYSTIMESTAMP,
    FOREIGN KEY (player_id) REFERENCES Player(player_id),
    FOREIGN KEY (match_id) REFERENCES MatchGame(match_id),
    FOREIGN KEY (odds_id) REFERENCES Odds(odds_id)
);

-- PLAYER TRANSACTION
CREATE TABLE Player_Transaction (
    transaction_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id NUMBER,
    amount NUMBER(10,2),
    transaction_type VARCHAR2(20) CHECK (transaction_type IN ('deposit', 'withdrawal', 'bet')),
    transaction_date DATE DEFAULT SYSDATE,
    transaction_time TIMESTAMP DEFAULT SYSTIMESTAMP,
    status VARCHAR2(20),
    FOREIGN KEY (player_id) REFERENCES Player(player_id)
);

-- sqlplus BetSyncDB/1234@localhost:1521/XEPDB1 @betsync_schema.sql
